services:
  mesh:
    container_name: mesh
    image: heurist-mesh:local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/mesh_health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
