# .github/workflows/deploy_mesh.yml
name: Deploy Mesh to Production

on:
  push:
    branches:
      - main
    paths:
      - 'mesh/**'
      - 'core/**'
      - 'clients/**'
      - 'agents/**'
      - 'interfaces/**'
      - 'mesh_api.py'
      - 'mesh_manager.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment webhook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.DEPLOY_WEBHOOK_SECRET }}
          data: '{"repository": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "commits": ${{ toJson(github.event.commits) }}}'
